/* Medi – Edlando Medicare education assistant. Rule-based, runs in the browser, stores no personal data. */
(function(){
var PHONE='(346) 454-5129',TEL='tel:+13464545129';
var HUMAN='<br><br>Want help from a person? <a href="'+TEL+'">Call a licensed agent at '+PHONE+'</a>, <a href="questionnaire.html">book a free review</a>, or contact your free, unbiased <a href="https://www.shiphelp.org" target="_blank" rel="noopener">SHIP counselor</a> or 1-800-MEDICARE (1-800-633-4227).';
function phase(){var d=new Date(),k=(d.getMonth()+1)*100+d.getDate();
 if(k>=1015&&k<=1207)return 'Annual Enrollment is open now (Oct 15 – Dec 7). Changes start January 1.';
 if(k>=1001&&k<1015)return 'Plan info for next year is out. Annual Enrollment opens October 15.';
 if(k>=101&&k<=331)return 'Medicare Advantage Open Enrollment runs Jan 1 – Mar 31 for people already in an Advantage plan.';
 return 'The next Annual Enrollment Period is October 15 – December 7.';}
var R=[
 [/(chest pain|emergency|suicid|kill myself|hurt myself|can.?t breathe)/,'If this is an emergency, please call 911 now. For emotional crisis support, call or text 988.'],
 [/(enroll me|sign me up|switch|cancel|which plan|best plan|should i|recommend|choose)/,'I can explain options, but choosing or enrolling in a plan is an important decision that a licensed person should help you with. I don\u2019t recommend specific plans.'],
 [/(scam|called me|asking for my medicare number|new card)/,'Medicare will not call you to ask for your Medicare number. Don\u2019t share it. Report suspicious calls to 1-800-MEDICARE or your <a href="https://smpresource.org" target="_blank" rel="noopener">Senior Medicare Patrol</a>.'],
 [/part a|hospital/,'Part A is hospital insurance. It helps cover inpatient hospital stays, skilled nursing care after a qualifying hospital stay, hospice, and some home health. Most people pay no monthly premium if they worked about 10 years. Note: being under \u201cobservation\u201d is not the same as being admitted.'],
 [/part b|doctor|outpatient/,'Part B is medical insurance. It covers doctor visits, outpatient care, preventive services, lab tests, and medical equipment. There is a monthly premium and a yearly deductible, then usually 20% coinsurance. Signing up late can mean a lifelong penalty.'],
 [/part c|advantage|hmo|ppo/,'Part C (Medicare Advantage) plans are offered by private companies approved by Medicare. They cover everything Parts A and B cover, often include drug coverage and extras, and have a yearly out-of-pocket limit. Many use provider networks and prior authorization.'],
 [/part d|drug|prescription|medication|formulary|tier|pharmacy/,'Part D covers prescription drugs, through a standalone plan or a Medicare Advantage plan. Each plan has a drug list (formulary) with tiers \u2014 lower tiers, usually generics, cost less. There is a yearly out-of-pocket cap on drug costs, and Extra Help can lower costs for people with limited income. Drug lists change each year, so check yours during enrollment.'],
 [/medigap|supplement/,'Medigap (Medicare Supplement) plans help pay costs Original Medicare doesn\u2019t, like the 20% coinsurance. They work with Original Medicare, not Medicare Advantage. The best time to buy is usually your 6-month Medigap open enrollment after Part B starts.'],
 [/extra help|lis|low income|medicaid/,'Extra Help (Low-Income Subsidy) helps pay Part D costs. People with Medicaid and Medicare may qualify for special plans too. A licensed agent or SHIP counselor can check eligibility with you.'],
 [/(when|enroll|aep|deadline|open enrollment|turning 65|sign up)/,'IEP: 7 months around your 65th birthday month. AEP: Oct 15 – Dec 7 each year. MA Open Enrollment: Jan 1 – Mar 31. Special Enrollment Periods apply after events like moving or losing employer coverage.']
];
function answer(q){q=q.toLowerCase();for(var i=0;i<R.length;i++){if(R[i][0].test(q))return R[i][1]+(i===0?'':HUMAN);}
 return 'I can explain Medicare Parts A, B, C, D, Medigap, Extra Help, and enrollment dates. Try asking \u201cWhat does Part D cover?\u201d'+HUMAN;}
var css='#medi-btn{position:fixed;right:18px;bottom:18px;z-index:9999;background:#1e40af;color:#fff;border:0;border-radius:30px;padding:14px 20px;font:600 16px system-ui;box-shadow:0 4px 14px rgba(0,0,0,.25);cursor:pointer}#medi-box{position:fixed;right:18px;bottom:80px;z-index:9999;width:min(360px,calc(100vw - 36px));max-height:70vh;display:none;flex-direction:column;background:#fff;border-radius:14px;box-shadow:0 8px 30px rgba(0,0,0,.25);font:16px/1.45 system-ui;color:#1f2937;overflow:hidden}#medi-box.open{display:flex}#medi-h{background:#1e40af;color:#fff;padding:12px 14px;font-weight:600;display:flex;justify-content:space-between}#medi-h button{background:none;border:0;color:#fff;font-size:20px;cursor:pointer}#medi-log{padding:12px;overflow-y:auto;flex:1}.medi-m{margin:6px 0;padding:9px 12px;border-radius:10px;background:#f1f5f9}.medi-u{background:#dbeafe;text-align:right}#medi-log a{color:#1e40af}#medi-chips{padding:0 12px 6px;display:flex;flex-wrap:wrap;gap:6px}#medi-chips button{border:1px solid #1e40af;background:#fff;color:#1e40af;border-radius:16px;padding:5px 10px;font-size:14px;cursor:pointer}#medi-f{display:flex;border-top:1px solid #e5e7eb}#medi-f input{flex:1;border:0;padding:12px;font-size:16px}#medi-f button{border:0;background:#1e40af;color:#fff;padding:0 16px;cursor:pointer}.medi-d{font-size:12px;color:#6b7280;padding:6px 12px}';
var st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
var b=document.createElement('button');b.id='medi-btn';b.textContent='Ask Medi about Medicare';
var box=document.createElement('div');box.id='medi-box';box.setAttribute('role','dialog');box.setAttribute('aria-label','Medicare help chat');
box.innerHTML='<div id="medi-h">Medi \u2013 Medicare Helper<button aria-label="Close">\u00d7</button></div><div id="medi-log" aria-live="polite"></div><div id="medi-chips"></div><form id="medi-f"><input aria-label="Type your question" placeholder="Ask a Medicare question\u2026" maxlength="300"><button>Send</button></form><div class="medi-d">Educational info only, not a plan recommendation. Please don\u2019t share your Medicare or Social Security number here. We do not offer every plan available in your area; contact Medicare.gov, 1-800-MEDICARE, or your local SHIP for all options.</div>';
document.body.appendChild(b);document.body.appendChild(box);
var log=box.querySelector('#medi-log');
function add(t,u){var d=document.createElement('div');d.className='medi-m'+(u?' medi-u':'');if(u)d.textContent=t;else d.innerHTML=t;log.appendChild(d);log.scrollTop=log.scrollHeight;}
function ask(q){if(!q.trim())return;if(/\b\d{3}-?\d{2}-?\d{4}\b|\b\d[a-z][a-z0-9]\d-?[a-z][a-z0-9]\d-?[a-z]{2}\d{2}\b/i.test(q)){add('[number hidden]',1);add('For your privacy, please don\u2019t share ID numbers here.'+HUMAN);return;}add(q,1);setTimeout(function(){add(answer(q));},250);if(window.gtag)gtag('event','medi_question');}
['Part A','Part B','Part C','Part D','Drug tiers','Enrollment dates','Talk to an agent'].forEach(function(c){var x=document.createElement('button');x.type='button';x.textContent=c;x.onclick=function(){ask(c==='Talk to an agent'?'which plan should i choose':c==='Drug tiers'?'formulary tier':c==='Enrollment dates'?'when enroll':c);};box.querySelector('#medi-chips').appendChild(x);});
var started=0;b.onclick=function(){box.classList.toggle('open');if(!started){started=1;add('Hi, I\u2019m Medi. I explain Medicare in plain language. '+phase());}};
box.querySelector('#medi-h button').onclick=function(){box.classList.remove('open');};
box.querySelector('#medi-f').onsubmit=function(e){e.preventDefault();var i=this.querySelector('input');ask(i.value);i.value='';};
})();
